// STATUS: NOT STARTED

#ifndef GCC_SRC_NEWLIB_LIBM_MATH_EF_ATAN2_H
#define GCC_SRC_NEWLIB_LIBM_MATH_EF_ATAN2_H


float __ieee754_atan2f(float y, float x);

#endif // GCC_SRC_NEWLIB_LIBM_MATH_EF_ATAN2_H
