// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_IMPURE_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_IMPURE_H

extern _reent *_impure_ptr;


#endif // SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_IMPURE_H
