// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_E_POW_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_E_POW_H


double __ieee754_pow(double x, double y);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_E_POW_H
