// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_KF_COS_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_KF_COS_H


float __kernel_cosf(float x, float y);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_KF_COS_H
