// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_S_FLOOR_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_S_FLOOR_H


double floor(double x);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_S_FLOOR_H
