// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_ISNAN_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_ISNAN_H

int isnanf(float x);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_ISNAN_H
