// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_W_ATAN2_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_W_ATAN2_H

double atan2(double y, double x);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_W_ATAN2_H
