// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_W_POW_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_W_POW_H

double pow(double x, double y);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_W_POW_H
