// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_ACOS_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_ACOS_H

float acosf(float x);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_ACOS_H
