// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_SQRT_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_SQRT_H

float sqrtf(float x);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_SQRT_H
