// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_STRCASECMP_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_STRCASECMP_H

int strcasecmp(char *s1, char *s2);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_STRCASECMP_H
