// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_FFLUSH_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_FFLUSH_H

int fflush(FILE *fp);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_FFLUSH_H
