// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_REFILL_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_REFILL_H

int __srefill(FILE *fp);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_REFILL_H
