// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_WSETUP_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_WSETUP_H

int __swsetup(FILE *fp);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_WSETUP_H
