// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_S_COPYSIGN_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_S_COPYSIGN_H

double copysign(double x, double y);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_S_COPYSIGN_H
