// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_SCALBN_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_SCALBN_H


float scalbnf(float x, int n);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_SCALBN_H
