// STATUS: NOT STARTED

#ifndef GCC_SRC_NEWLIB_LIBC_STDIO_UNGETC_H
#define GCC_SRC_NEWLIB_LIBC_STDIO_UNGETC_H

int __submore(FILE *fp);
int ungetc(int c, FILE *fp);

#endif // GCC_SRC_NEWLIB_LIBC_STDIO_UNGETC_H
