// STATUS: NOT STARTED

#ifndef GCC_SRC_NEWLIB_LIBC_STDIO_VSPRINTF_H
#define GCC_SRC_NEWLIB_LIBC_STDIO_VSPRINTF_H

int vsprintf(char *str, char *fmt, va_list ap);

#endif // GCC_SRC_NEWLIB_LIBC_STDIO_VSPRINTF_H
