// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_ACOS_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_ACOS_H


float __ieee754_acosf(float x);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_ACOS_H
