// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_ASIN_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_ASIN_H


float __ieee754_asinf(float x);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_ASIN_H
