// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_POW_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_POW_H


float __ieee754_powf(float x, float y);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_POW_H
