// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_REM_PIO2_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_REM_PIO2_H


__int32_t __ieee754_rem_pio2f(float x, float *y);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_REM_PIO2_H
