// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_ATAN_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_ATAN_H


float atanf(float x);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_ATAN_H
