// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_FLOOR_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_FLOOR_H


float floorf(float x);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_FLOOR_H
