// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_FABS_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_FABS_H

float fabsf(float x);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_FABS_H
