// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_ATAN2_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_ATAN2_H

float atan2f(float y, float x);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_ATAN2_H
