// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_ASIN_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_ASIN_H

float asinf(float x);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_ASIN_H
