// STATUS: NOT STARTED

#ifndef GAME_CHR_CHR_H
#define GAME_CHR_CHR_H

struct chrsoundgroup_s {
	short int hitsounds[18];
	short int deathsounds[6];
	short int frontsounds[1];
};

typedef chrsoundgroup_s chrsoundgroup;

struct chrdesc_s {
	short int longname;
	short int name;
	chrsoundgroup *sounds;
	int propnum;
	int frontpropnum;
	int appearancesubtype;
	int sex;
	float height;
	float crouchheight;
	float eyedist;
	float hardrad;
	float softrad;
	float scale;
	int animpersonality;
	int favouritegun;
	int easyskill;
	int normalskill;
	int hardskill;
};

typedef chrdesc_s chrdesc;
extern chrsoundgroup soundgroup_F_COP;
extern chrsoundgroup soundgroup_F_ANGEL;
extern chrsoundgroup soundgroup_M_MRBIG;
extern chrsoundgroup soundgroup_M_FUTCOP;
extern chrsoundgroup soundgroup_M_GRAVEN;
extern chrsoundgroup soundgroup_M_LUMBERJACK;
extern chrsoundgroup soundgroup_M_CAPT_ASH;
extern chrsoundgroup soundgroup_C_BADASS;
extern chrsoundgroup soundgroup_F_LADYJAYNE;
extern chrsoundgroup soundgroup_M_RESDOG;
extern chrsoundgroup soundgroup_F_SCIENTIST;
extern chrsoundgroup soundgroup_F_FUTCOP;
extern chrsoundgroup soundgroup_F_STEWARDESS;
extern chrsoundgroup soundgroup_X_BUNNYGIRL;
extern chrsoundgroup soundgroup_F_SWAT;
extern chrsoundgroup soundgroup_U_PRIEST;
extern chrsoundgroup soundgroup_M_WAITER;
extern chrsoundgroup soundgroup_Z_JACKET;
extern chrsoundgroup soundgroup_Z_SKULL;
extern chrsoundgroup soundgroup_U_OVERALL;
extern chrsoundgroup soundgroup_Z_GENERIC;
extern chrsoundgroup soundgroup_Z_SKULL2;
extern chrsoundgroup soundgroup_Z_BROWN;
extern chrsoundgroup soundgroup_Z_GREEN;
extern chrsoundgroup soundgroup_U_HICK;
extern chrsoundgroup soundgroup_Z_POLICE;
extern chrsoundgroup soundgroup_X_DUCKMAN;
extern chrsoundgroup soundgroup_M_COP;
extern chrsoundgroup soundgroup_X_IMPERSONATOR;
extern chrsoundgroup soundgroup_C_TUXEDO;
extern chrsoundgroup soundgroup_U_INSECT;
extern chrsoundgroup soundgroup_F_ROBOT;
extern chrsoundgroup soundgroup_Z_TEETHMUMMY;
extern chrsoundgroup soundgroup_Z_EYESMUMMY;
extern chrsoundgroup soundgroup_F_RESDOG;
extern chrsoundgroup soundgroup_F_ZOMBIE;
extern chrsoundgroup soundgroup_U_FISHWIFE;
extern chrsoundgroup soundgroup_F_CHEERLEADER;
extern chrsoundgroup soundgroup_C_SIAMESE;
extern chrsoundgroup soundgroup_X_GINGER;
extern chrsoundgroup soundgroup_RED_ALIEN;
extern chrsoundgroup soundgroup_GREEN_ALIEN;
extern chrsoundgroup soundgroup_A_PILLAR;
extern chrsoundgroup soundgroup_M_PEEKABOO;
extern chrsoundgroup soundgroup_F_CLEANER;
extern chrsoundgroup soundgroup_M_SWAT;
extern chrsoundgroup soundgroup_M_SWAT2;
extern chrsoundgroup soundgroup_M_SWATMASK;
extern chrsoundgroup soundgroup_M_SWATMASK2;
extern chrsoundgroup soundgroup_M_VEILMASK;
extern chrsoundgroup soundgroup_M_MILGAS;
extern chrsoundgroup soundgroup_M_SUITHOOD;
extern chrsoundgroup soundgroup_F_CYBORG;
extern chrsoundgroup soundgroup_M_CULTIST;
extern chrsoundgroup soundgroup_F_PRIESTESS;
extern chrsoundgroup soundgroup_F_ALIEN;
extern chrsoundgroup soundgroup_M_ROBOT;
extern chrsoundgroup soundgroup_M_CLEANER;
extern chrsoundgroup soundgroup_M_COOK;
extern chrsoundgroup soundgroup_X_ROBOFISH;
extern chrsoundgroup soundgroup_A_FLOAT;
extern chrsoundgroup soundgroup_M_SMARINE;
extern chrsoundgroup soundgroup_Z_SPLITTER1;
extern chrsoundgroup soundgroup_Z_SPLITTER2;
extern chrsoundgroup soundgroup_Z_SPLITTER3;
extern chrsoundgroup soundgroup_Z_SPLITTER4;
extern chrsoundgroup soundgroup_BLUEROBOT;
extern chrsoundgroup soundgroup_M_GASMASK_SPFORCE;
extern chrsoundgroup soundgroup_M_GASMASK_WOOD;
extern chrsoundgroup soundgroup_M_GASMASK_ARTIC;
extern chrsoundgroup soundgroup_M_GASMASK_ZOMBIE;
extern chrsoundgroup soundgroup_M_GASMASK_DESERT;
extern chrsoundgroup soundgroup_M_BERET_ARTIC;
extern chrsoundgroup soundgroup_M_BERET_DESERT;
extern chrsoundgroup soundgroup_M_BERET_WOOD;
extern chrsoundgroup soundgroup_M_BERET_SPFORCE;
extern chrsoundgroup soundgroup_F_SOLDIER_ARTIC;
extern chrsoundgroup soundgroup_F_SOLDIER_DESERT;
extern chrsoundgroup soundgroup_F_SOLDIER_HAT;
extern chrsoundgroup soundgroup_F_SOLDIER_SPFORCE;
extern chrsoundgroup soundgroup_F_SOLDIER_WOOD;
extern chrsoundgroup soundgroup_F_SOLDIER_ZOMBIE;
extern chrsoundgroup soundgroup_M_VEIL_ARTIC;
extern chrsoundgroup soundgroup_M_VEIL_DESERT;
extern chrsoundgroup soundgroup_M_VEIL_SPFORCE;
extern chrsoundgroup soundgroup_M_VEIL_WOOD;
extern chrsoundgroup soundgroup_B_MONKEY;
extern chrsoundgroup soundgroup_F_SKINNY_HOOER;
extern chrsoundgroup soundgroup_F_SALOON_HOOER;
extern chrsoundgroup soundgroup_M_BERET_SOLDIER_ZOMBIE;
extern chrsoundgroup soundgroup_M_HELMET_SOLDIER_ZOMBIE;
extern chrsoundgroup soundgroup_M_VEIL_SOLDIER_ZOMBIE;
extern chrsoundgroup soundgroup_M_SOLDIER_MUTANT;
extern chrsoundgroup soundgroup_WOOD_GOLEM;
extern chrsoundgroup soundgroup_STONE_GOLEM;
extern chrsoundgroup soundgroup_F_JUNGLE_QUEEN;
extern chrsoundgroup soundgroup_F_WITCH;
extern chrsoundgroup soundgroup_M_CURTAINS_COWBOY;
extern chrsoundgroup soundgroup_M_EVIL_COWBOY;
extern chrsoundgroup soundgroup_M_MEXICAN;
extern chrsoundgroup soundgroup_M_MINER;
extern chrsoundgroup soundgroup_M_BRACES_THUG;
extern chrsoundgroup soundgroup_M_GODFATHER;
extern chrsoundgroup soundgroup_M_MAIN_COWBOY;
extern chrsoundgroup soundgroup_F_ISLA_NADIR;
extern chrsoundgroup soundgroup_F_JESTER;
extern int flinchsfx[80];
extern chrdata *chrinfo;
extern chrdesc chrs[0];
extern int chrnew_lastchrnum;

void chrRestart();
void chrReset();
void chrEnd();
void chrConfirmLastHitPart();
int chrGetLastHitPart();
void chrSetLastHitPart(int Part);
void chrAddFloorMoveToPos(int Chr, float *Pos, float *pDir);
boolean chrLineTestChr(prop *pProp, float *StartPosOrig, float *DirOrig, float *EndPos, boolean Infinite, float *HitPos, float *HitNorm, int CollisionTypeFlag);
boolean chrSwipeTestChr(prop *pProp, float *SwipePosCentreO, float *SwipePosStartO, float *SwipePosEndO, float *HitPos, float *HitNorm);
boolean chrTypeIsZombie(int chrtype);
prop* chrNew(int chrnumuse, int chrnumoriginal, int frontend, int id, float x, float y, float z, float roty, int padextref, boolean InitBounds);
void chrPlaceOnPad(chrdata *chr, int padnum);
int chrGetChrLimbProp(int chrtypeuse, int chrtypeoriginal, int limb);
void chrRelocateLimbs(int chrnumuse, int chrnumoriginal);
void chrDie(chrdata *chr);
void chrRespawn(chrdata *chr);
void chrSelectTeam(chrdata *cd);
void chrPreload(int chrnumuse, int chrnumoriginal);
void chrResetGunsAndAmmo(chrdata *chr);
void chrClearGuns(chrdata *chr);
void chrSelectDeathAnim(prop *p, int bullettype, float *bulletpos, float *bulletdir, int parthit, int deathflag);
void updateTeamFlags(prop *p, prop *bag, int flag);
int chrCountKills(chrdata *chr);
void chrAddKills(chrdata *cd, int victimid, int addpts);
int chrCountLosses(chrdata *chr);
int teamGetScore(int chrteam);
int chrGetScore(int chrnum);
void chrAddScore(chrdata *cd, int addpts);
int chrGetTimeSinceGunFire(chrdata *cd);
void chrCalcAimPos(chrdata *cd);

#endif // GAME_CHR_CHR_H
