// STATUS: NOT STARTED

#ifndef GCC_SRC_NEWLIB_LIBC_STRING_STRCASECMP_H
#define GCC_SRC_NEWLIB_LIBC_STRING_STRCASECMP_H

int strcasecmp(char *s1, char *s2);

#endif // GCC_SRC_NEWLIB_LIBC_STRING_STRCASECMP_H
