// STATUS: NOT STARTED

#ifndef GCC_SRC_NEWLIB_LIBM_COMMON_SF_COPYSIGN_H
#define GCC_SRC_NEWLIB_LIBM_COMMON_SF_COPYSIGN_H

float copysignf(float x, float y);

#endif // GCC_SRC_NEWLIB_LIBM_COMMON_SF_COPYSIGN_H
