// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_CLOSER_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_CLOSER_H

int _close_r(_reent *ptr, int fd);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_CLOSER_H
