// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_MALLOC_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_MALLOC_H

void* malloc(size_t nbytes);
void free(void *aptr);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_MALLOC_H
