// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_FIPRINTF_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_FIPRINTF_H

int fiprintf(FILE *fp, char *fmt);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_FIPRINTF_H
