// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_MAKEBUF_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_MAKEBUF_H

void __smakebuf(FILE *fp);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_MAKEBUF_H
