// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_SSCANF_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_SSCANF_H

int sscanf(char *str, char *fmt);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBC_STDIO_SSCANF_H
