// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_S_FINITE_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_S_FINITE_H

int finite(double x);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_S_FINITE_H
