// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_S_RINT_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_S_RINT_H


double rint(double x);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_S_RINT_H
