// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_S_SCALBN_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_S_SCALBN_H


double scalbn(double x, int n);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_S_SCALBN_H
