// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_COPYSIGN_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_COPYSIGN_H

float copysignf(float x, float y);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_COPYSIGN_H
