// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_FINITE_H
#define SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_FINITE_H

int finitef(float x);

#endif // SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_FINITE_H
