// STATUS: NOT STARTED

#ifndef SCE_EE_GCC_SRC_NEWLIB_LIBC_CTYPE_CTYPE__H
#define SCE_EE_GCC_SRC_NEWLIB_LIBC_CTYPE_CTYPE__H

extern char _ctype_[257];


#endif // SCE_EE_GCC_SRC_NEWLIB_LIBC_CTYPE_CTYPE__H
